version: '3.8'

services:
  backend:
    build: ./cv-generator-backend
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///app.db
    volumes:
      - ./cv-generator-backend/src/database:/app/src/database
      - /tmp:/tmp
    depends_on:
      - db

  frontend:
    build: ./cv-generator-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:5002

  db:
    image: sqlite:latest
    volumes:
      - db_data:/var/lib/sqlite

volumes:
  db_data:
